import safarictl
import random
import requests
import time
from faker import Faker
fake = Faker()

restaurants = ["America's Incredible Pizza Company",
"Anchor Bar",
"Angus Steakhouse",
"Anjappar Chettinad Restaurant",
"Annalakshmi",
"Applebee's",
"Arab Udupi",
"ASK Italian",
"Bahama Breeze",
"Bakers Square",
"Bar Louie Restaurants",
"Baton Rouge",
"Becks Prime",
"Beef O'Brady's",
"Beefeater",
"Belgo",
"Bella Italia",
"Benihana",
"Bennigan's",
"Bertucci's",
"Bickford's",
"Big Boy",
"Bill's",
"BJ's Restaurants",
"Black Angus Steakhouse",
"Black-eyed Pea",
"Bob Evans Restaurants",
"Bob's Big Boy",
"Bonefish Grill",
"Boomarang Diner",
"Boston Pizza",
"Bread Ahead",
"Brewers Fayre",
"Brio Tuscan Grille",
"Brotzeit",
"Bubba Gump Shrimp Company",
"Buca di Beppo",
"Buffalo Grill",
"Buffalo Wild Wings",
"Buffalo Wings and Rings",
"Buffalo's Cafe",
"Burger Fuel",
"Byron Hamburgers",
"Cabalen",
"Cactus Club Cafe",
"Café Rouge",
"California Pizza Kitchen",
"Camille's Sidewalk Cafe",
"Cantina Mariachi",
"The Capital Grille",
"Carino's Italian",
"Carlos'n Charlie's",
"Carluccio's Ltd",
"Carrabba's Italian Grill",
"Carrows",
"Champps Americana",
"Charlie Brown's Fresh Grill",
"Cheba Hut",
"Cheddar's Scratch Kitchen",
"The Cheesecake Factory",
"Chevys Fresh Mex",
"Chi-Chi's",
"Chickie's and Pete's",
"Chili's",
"Chiquito",
"Chuck-A-Rama",
"Chuck E Cheese's",
"Chuy's",
"Cicis",
"Claim Jumper",
"Coco's Bakery",
"Congo Grille",
"Cooper's Hawk Winery and Restaurants",
"Copeland's",
"Cora",
"Côte",
"Cotton Patch Café",
"The Counter",
"Crabby Joe's Tap and Grill",
"Cracker Barrel",
"Dametra Cafe",
"Dave and Buster's",
"Del Frisco's Double Eagle Steak House",
"Dencio's",
"Denny's",
"Dick's Last Resort",
"Dickey's Barbecue Pit",
"Din Tai Fung",
"Dindigul Thalappakatti Restaurant",
"Dishoom",
"Dixie Chili and Deli",
"Dunn's",
"Earls",
"East Side Mario's",
"Eat'n Park",
"Eddie Rocket's",
"Eddie V's Prime Seafood",
"Ed's Easy Diner",
"El Fenix",
"El Torito",
"Elephant Bar",
"Famous Dave's",
"Feng Sushi",
"Fleming's Prime Steakhouse and Wine Bar",
"Flunch",
"Fogo de Chão",
"Fox's Pizza Den",
"Franco Manca",
"Frankie and Benny's",
"Fresh to Order",
"Friendly's",
"Frisch's Big Boy",
"Garduño's",
"Gator's Dockside",
"Gerry's Grill",
"Giraffe World Kitchen",
"Golden Corral",
"Golden Nugget Pancake House",
"Gourmet Burger Kitchen",
"Graffiti Junktion",
"Grandy's",
"Ground Round",
"Guzman y Gomez",
"Haidilao",
"Happy Joe's",
"Happy's Pizza",
"Hard Rock Cafe",
"Harry Ramsden's",
"Harvester",
"Hash House a go go",
"Hippopotamus",
"Hog's Australia's Steakhouse",
"Hooters",
"HopCat",
"Hoss's Steak and Sea House",
"Houlihan's",
"Houston's Restaurant",
"Huddle House",
"HuHot Mongolian Grill",
"Hurricane Grill and Wings",
"Hwy 55 Burgers Shakes and Fries",
"IHOP",
"Islands Fine Burgers and Drinks",
"J Alexander's",
"Jack Astor's Bar and Grill",
"Jensen's Bøfhus",
"Jerry's J-Boy Restaurants",
"Jim's Restaurants",
"Jimmy Buffett's Margaritaville",
"Jimmy's Restaurants",
"Jinya Ramen Bar",
"Joe's Crab Shack",
"Joey's Seafood Restaurants",
"Johnny Rockets",
"John's Incredible Pizza Company",
"The Keg",
"Kelseys Original Roadhouse",
"Ker's WingHouse Bar and Grill",
"Kings Family Restaurants",
"Kona Grill",
"La Porchetta",
"La Tasca",
"Landry's Seafood",
"Larkburger",
"Las Iguanas",
"Laughing Planet",
"Lawry's",
"Lazy Dog Restaurant and Bar",
"Lee Roy Selmon's",
"Lee's Famous Recipe Chicken",
"Legal Sea Foods",
"Little Anita's",
"Little Sheep Group",
"Loch Fyne Restaurants",
"Logan's Roadhouse",
"LongHorn Steakhouse",
"Luby's",
"Lucille's Smokehouse Bar-B-Que",
"Maggiano's Little Italy",
"Maid-Rite",
"Mandarin Restaurant",
"Mao",
"Marie Callender's",
"Marrybrown",
"Mary Brown's",
"Max and Erma's",
"McCormick and Schmick's",
"MCL Restaurant and Bakery",
"Medieval Times",
"Mellow Mushroom",
"The Melting Pot",
"Mikes",
"Milano",
"Milestones Grill and Bar",
"Miller's Ale House",
"Mimi's Cafe",
"Monical's Pizza",
"Montana Mike's",
"Montana's BBQ and Bar",
"Moo Moo Restaurant",
"Morton's The Steakhouse",
"Moxie's Grill and Bar",
"Mr Gatti's Pizza",
"Mr Mike's",
"Nickels Grill and Bar",
"Ocean Prime",
"O'Charley's",
"Ojos Locos",
"OK Diner",
"Old Chicago Pizza and Taproom",
"Old Country Buffet",
"The Old Spaghetti Factory",
"Olga's Kitchen",
"Olive Garden",
"On the Border Mexican Grill and Cantina",
"The Original Pancake House",
"Outback Steakhouse",
"P F Chang's China Bistro",
"Pamela's Diner",
"Pancake Parlour",
"Pancho's Mexican Buffet",
"Panda Inn",
"Pappadeaux",
"Peppes Pizza",
"Perkins Restaurant and Bakery",
"Peter Piper Pizza",
"Phở Hòa",
"Pizza Boli's",
"Pizza Celentano",
"Pizza Hut",
"Pizza Inn",
"PizzaExpress",
"Planet Hollywood",
"Po' Folks",
"Ponderosa and Bonanza Steakhouses",
"Prezzo",
"Pyongyang",
"Quaker Steak and Lube",
"Quanjude",
"Rainforest Cafe",
"Red Hot and Blue",
"Red Lobster",
"Red Robin",
"Redneck Heaven",
"Redstone American Grill",
"Ricky's All Day Grill",
"Roadhouse Grill",
"Romano's Macaroni Grill",
"Rosa's Cafe",
"Roscoe's House of Chicken and Waffles",
"Round Table Pizza",
"Roy's",
"Rua do Cunha",
"Ruby Tuesday",
"Ruby's Diner",
"Rusty Bucket Restaurant and Tavern",
"Ruth's Chris Steak House",
"Saizeriya",
"Salisbury House",
"Saltgrass Steak House",
"Sam Woo Restaurant",
"Saravana Bhavan",
"Schnitz",
"Scores",
"Seasons 52",
"Señor Frog's",
"Shari's Cafe and Pies",
"Shoeless Joe's",
"Shoney's",
"Sirloin Stockade",
"Sizzler",
"Sizzler International",
"Skyline Chili",
"Smitty's",
"Smoke's Poutinerie",
"Smokey Bones",
"Sonny Bryan's Smokehouse",
"Sonny's BBQ",
"Souper Salad",
"Spaghetti Warehouse",
"Spur Steak Ranches",
"St-Hubert",
"Steak 'n Shake",
"Sticks'n'Sushi",
"Stoney River Legendary Steaks",
"Strada",
"Swiss Chalet",
"Symposium Cafe",
"Table Table",
"Taco Palenque",
"Tahoe Joe's",
"Texas de Brazil",
"Texas Roadhouse",
"TGI Fridays",
"Thaï Express",
"Thai Express",
"Tijuana Flats",
"Tilted Kilt Pub and Eatery",
"Toby Carvery",
"Tony Roma's",
"Trader Vic's",
"Tumbleweed Tex Mex Grill and Margarita Bar",
"Twin Peaks",
"Uno Pizzeria and Grill",
"Valentino's",
"Vic and Anthony's Steakhouse",
"Village Inn",
"Waffle House",
"Wagamama",
"Wahaca",
"Wahlburgers",
"Walker Bros",
"Weathervane Restaurant",
"Weber Grill Restaurant",
"Western Sizzlin'",
"Wienerwald",
"Wildwood Kitchen",
"Wimpy",
"Wimpy's Diner",
"Wingstop",
"Yard House",
"Zizzi"]

cities = ["Abbott",
"Abernathy",
"Abilene",
"Ackerly",
"Addison",
"Adrian",
"Agua Dulce",
"Alamo",
"Alamo Heights",
"Alba",
"Albany",
"Aledo",
"Alice",
"Allen",
"Alma",
"Alpine",
"Alto",
"Alton",
"Alvarado",
"Alvin",
"Alvord",
"Amarillo",
"Ames",
"Amherst",
"Anahuac",
"Anderson",
"Andrews",
"Angleton",
"Angus",
"Anna",
"Annetta",
"Annetta North",
"Annetta South",
"Annona",
"Anson",
"Anthony",
"Anton",
"Appleby",
"Aquilla",
"Aransas Pass",
"Archer City",
"Arcola",
"Argyle",
"Arlington",
"Arp",
"Asherton",
"Aspermont",
"Athens",
"Atlanta",
"Aubrey",
"Aurora",
"Austin",
"Austwell",
"Avery",
"Avinger",
"Azle",
"Bailey",
"Bailey's Prairie",
"Baird",
"Balch Springs",
"Balcones Heights",
"Ballinger",
"Balmorhea",
"Bandera",
"Bangs",
"Bardwell",
"Barry",
"Barstow",
"Bartlett",
"Bartonville",
"Bastrop",
"Bay City",
"Bayou Vista",
"Bayside",
"Baytown",
"Bayview",
"Beach City",
"Bear Creek",
"Beasley",
"Beaumont",
"Beckville",
"Bedford",
"Bedias",
"Bee Cave",
"Beeville",
"Bellaire",
"Bellevue",
"Bellmead",
"Bells",
"Bellville",
"Belton",
"Benavides",
"Benbrook",
"Benjamin",
"Berryville",
"Bertram",
"Beverly Hills",
"Bevil Oaks",
"Big Lake",
"Big Sandy",
"Big Spring",
"Big Wells",
"Bishop",
"Bishop Hills",
"Blackwell",
"Blanco",
"Blanket",
"Bloomburg",
"Blooming Grove",
"Blossom",
"Blue Mound",
"Blue Ridge",
"Blum",
"Boerne",
"Bogata",
"Bonham",
"Bonney",
"Booker",
"Borger",
"Bovina",
"Bowie",
"Boyd",
"Brackettville",
"Brady",
"Brazoria",
"Brazos Country",
"Breckenridge",
"Bremond",
"Brenham",
"Briarcliff",
"Briaroaks",
"Bridge City",
"Bridgeport",
"Broaddus",
"Bronte",
"Brookshire",
"Brookside Village",
"Browndell",
"Brownfield",
"Brownsboro",
"Brownsville",
"Brownwood",
"Bruceville-Eddy",
"Bryan",
"Bryson",
"Buckholts",
"Buda",
"Buffalo",
"Buffalo Gap",
"Buffalo Springs",
"Bullard",
"Bulverde",
"Bunker Hill Village",
"Burkburnett",
"Burke",
"Burleson",
"Burnet",
"Burton",
"Byers",
"Bynum",
"Cactus",
"Caddo Mills",
"Caldwell",
"Callisburg",
"Calvert",
"Cameron",
"Campbell",
"Camp Wood",
"Canadian",
"Caney City",
"Canton",
"Canyon",
"Carbon",
"Carl's Corner",
"Carmine",
"Carrizo Springs",
"Carrollton",
"Carthage",
"Cashion Community",
"Castle Hills",
"Castroville",
"Cedar Hill",
"Cedar Park",
"Celeste",
"Celina",
"Center",
"Centerville",
"Chandler",
"Channing",
"Charlotte",
"Chester",
"Chico",
"Childress",
"Chillicothe",
"China",
"China Grove",
"Chireno",
"Christine",
"Cibolo",
"Cisco",
"Clarendon",
"Clarksville",
"Clarksville City",
"Claude",
"Clear Lake Shores",
"Cleburne",
"Cleveland",
"Clifton",
"Clint",
"Clute",
"Clyde",
"Coahoma",
"Cockrell Hill",
"Coffee City",
"Coldspring",
"Coleman",
"College Station",
"Colleyville",
"Collinsville",
"Colmesneil",
"Colorado City",
"Columbus",
"Comanche",
"Combes",
"Combine",
"Commerce",
"Como",
"Conroe",
"Converse",
"Cool",
"Coolidge",
"Cooper",
"Coppell",
"Copperas Cove",
"Copper Canyon",
"Corinth",
"Corpus Christi",
"Corrigan",
"Corsicana",
"Cottonwood",
"Cottonwood Shores",
"Cotulla",
"Coupland",
"Cove",
"Covington",
"Coyote Flats",
"Crandall",
"Crane",
"Cranfills Gap",
"Crawford",
"Creedmoor",
"Cresson",
"Crockett",
"Crosbyton",
"Cross Plains",
"Cross Roads",
"Cross Timber",
"Crowell",
"Crowley",
"Crystal City",
"Cuero",
"Cumby",
"Cuney",
"Cushing",
"Cut and Shoot",
"Daingerfield",
"Daisetta",
"Dalhart",
"Dallas",
"Dalworthington Gardens",
"Danbury",
"Darrouzett",
"Dawson",
"Dayton",
"Dayton Lakes",
"Dean",
"Decatur",
"DeCordova",
"Deer Park",
"De Kalb",
"De Leon",
"Dell City",
"Del Rio",
"Denison",
"Denton",
"Denver City",
"Deport",
"DeSoto",
"Detroit",
"Devers",
"Devine",
"Diboll",
"Dickens",
"Dickinson",
"Dilley",
"Dimmitt",
"DISH",
"Dodd City",
"Dodson",
"Domino",
"Donna",
"Dorchester",
"Double Oak",
"Douglassville",
"Draper",
"Dripping Springs",
"Driscoll",
"Dublin",
"Dumas",
"Duncanville",
"Eagle Lake",
"Eagle Pass",
"Early",
"Earth",
"East Bernard",
"Eastland",
"East Mountain",
"Easton",
"East Tawakoni",
"Ector",
"Edcouch",
"Eden",
"Edgecliff Village",
"Edgewood",
"Edinburg",
"Edmonson",
"Edna",
"Edom",
"El Campo",
"El Cenizo",
"Eldorado",
"Electra",
"Elgin",
"Elkhart",
"El Lago",
"Ellinger",
"Elmendorf",
"El Paso",
"Elsa",
"Emhouse",
"Emory",
"Enchanted Oaks",
"Encinal",
"Ennis",
"Escobares",
"Estelline",
"Euless",
"Eureka",
"Eustace",
"Evant",
"Everman",
"Fairchilds",
"Fairfield",
"Fair Oaks Ranch",
"Fairview",
"Falfurrias",
"Falls City",
"Farmers Branch",
"Farmersville",
"Farwell",
"Fate",
"Fayetteville",
"Ferris",
"Flatonia",
"Florence",
"Floresville",
"Flower Mound",
"Floydada",
"Follett",
"Forest Hill",
"Forney",
"Forsan",
"Fort Stockton",
"Fort Worth",
"Franklin",
"Frankston",
"Fredericksburg",
"Freeport",
"Freer",
"Friendswood",
"Friona",
"Frisco",
"Fritch",
"Frost",
"Fruitvale",
"Fulshear",
"Fulton",
"Gainesville",
"Galena Park",
"Gallatin",
"Galveston",
"Ganado",
"Garden Ridge",
"Garland",
"Garrett",
"Garrison",
"Gary City",
"Gatesville",
"Georgetown",
"George West",
"Gholson",
"Giddings",
"Gilmer",
"Gladewater",
"Glenn Heights",
"Glen Rose",
"Godley",
"Goldsmith",
"Goldthwaite",
"Goliad",
"Golinda",
"Gonzales",
"Goodlow",
"Goodrich",
"Gordon",
"Goree",
"Gorman",
"Graford",
"Graham",
"Granbury",
"Grandfalls",
"Grand Prairie",
"Grand Saline",
"Grandview",
"Granger",
"Granite Shoals",
"Granjeno",
"Grapeland",
"Grapevine",
"Grays Prairie",
"Greenville",
"Gregory",
"Grey Forest",
"Groesbeck",
"Groom",
"Groves",
"Groveton",
"Gruver",
"Gun Barrel City",
"Gunter",
"Gustine",
"Hackberry",
"Hale Center",
"Hallettsville",
"Hallsburg",
"Hallsville",
"Haltom City",
"Hamilton",
"Hamlin",
"Happy",
"Hardin",
"Harker Heights",
"Harlingen",
"Hart",
"Haskell",
"Haslet",
"Hawk Cove",
"Hawkins",
"Hawley",
"Hays",
"Hearne",
"Heath",
"Hebron",
"Hedley",
"Hedwig Village",
"Helotes",
"Hemphill",
"Hempstead",
"Henderson",
"Henrietta",
"Hereford",
"Hewitt",
"Hickory Creek",
"Hico",
"Hidalgo",
"Hideaway",
"Higgins",
"Highland Haven",
"Highland Park",
"Highland Village",
"Hill Country Village",
"Hillcrest",
"Hillsboro",
"Hilshire Village",
"Hitchcock",
"Holiday Lakes",
"Holland",
"Holliday",
"Hollywood Park",
"Hondo",
"Honey Grove",
"Hooks",
"Horizon City",
"Horseshoe Bay",
"Houston",
"Howardwick",
"Howe",
"Hubbard",
"Hudson",
"Hudson Oaks",
"Hughes Springs",
"Humble",
"Hunters Creek Village",
"Huntington",
"Huntsville",
"Hurst",
"Hutchins",
"Hutto",
"Huxley",
"Idalou",
"Impact",
"Indian Lake",
"Industry",
"Ingleside",
"Ingleside on the Bay",
"Ingram",
"Iola",
"Iowa Colony",
"Iowa Park",
"Iraan",
"Iredell",
"Irving",
"Italy",
"Itasca",
"Ivanhoe",
"Jacinto City",
"Jacksboro",
"Jacksonville",
"Jamaica Beach",
"Jarrell",
"Jasper",
"Jayton",
"Jefferson",
"Jersey Village",
"Jewett",
"Joaquin",
"Johnson City",
"Jolly",
"Jones Creek",
"Jonestown",
"Josephine",
"Joshua",
"Jourdanton",
"Junction",
"Justin",
"Karnes City",
"Katy",
"Kaufman",
"Keene",
"Keller",
"Kemah",
"Kemp",
"Kempner",
"Kendleton",
"Kenedy",
"Kenefick",
"Kennard",
"Kennedale",
"Kerens",
"Kermit",
"Kerrville",
"Kilgore",
"Killeen",
"Kingsbury",
"Kingsville",
"Kirby",
"Kirbyville",
"Kirvin",
"Knollwood",
"Knox City",
"Kosse",
"Kountze",
"Kress",
"Krugerville",
"Krum",
"Kurten",
"Kyle",
"LaCoste",
"Lacy-Lakeview",
"Ladonia",
"La Feria",
"Lago Vista",
"La Grange",
"La Grulla",
"Laguna Vista",
"La Joya",
"Lake Bridgeport",
"Lake City",
"Lake Dallas",
"Lake Jackson",
"Lakeport",
"Lakeside",
"Lakeside",
"Lakeside City",
"Lake Tanglewood",
"Lakeview",
"Lakeway",
"Lakewood Village",
"Lake Worth",
"La Marque",
"Lamesa",
"Lampasas",
"Lancaster",
"La Porte",
"Laredo",
"Latexo",
"La Vernia",
"La Villa",
"Lavon",
"La Ward",
"Lawn",
"League City",
"Leakey",
"Leander",
"Leary",
"Lefors",
"Leona",
"Leonard",
"Leon Valley",
"Leroy",
"Levelland",
"Lewisville",
"Lexington",
"Liberty",
"Liberty Hill",
"Lincoln Park",
"Lindale",
"Linden",
"Lindsay",
"Lipan",
"Little Elm",
"Littlefield",
"Little River-Academy",
"Live Oak",
"Liverpool",
"Livingston",
"Llano",
"Lockhart",
"Lockney",
"Log Cabin",
"Lometa",
"Lone Oak",
"Lone Star",
"Longview",
"Loraine",
"Lorena",
"Lorenzo",
"Los Fresnos",
"Los Indios",
"Los Ybanez",
"Lott",
"Lovelady",
"Lowry Crossing",
"Lubbock",
"Lucas",
"Lueders",
"Lufkin",
"Luling",
"Lumberton",
"Lyford",
"Lytle",
"Mabank",
"McAllen",
"McCamey",
"McGregor",
"McKinney",
"McLean",
"McLendon-Chisholm",
"Madisonville",
"Magnolia",
"Malakoff",
"Malone",
"Manor",
"Mansfield",
"Manvel",
"Marble Falls",
"Marfa",
"Marietta",
"Marion",
"Marlin",
"Marquez",
"Marshall",
"Mart",
"Martindale",
"Mason",
"Matador",
"Mathis",
"Maud",
"Maypearl",
"Meadow",
"Meadowlakes",
"Meadows Place",
"Megargel",
"Melissa",
"Melvin",
"Memphis",
"Menard",
"Mercedes",
"Meridian",
"Merkel",
"Mertens",
"Mertzon",
"Mesquite",
"Mexia",
"Miami",
"Midland",
"Midlothian",
"Midway",
"Milano",
"Mildred",
"Miles",
"Milford",
"Miller's Cove",
"Millican",
"Millsap",
"Mineola",
"Mineral Wells",
"Mingus",
"Mission",
"Missouri City",
"Mobeetie",
"Mobile City",
"Monahans",
"Mont Belvieu",
"Montgomery",
"Moody",
"Moore Station",
"Moran",
"Morgan",
"Morgan's Point",
"Morgan's Point Resort",
"Morton",
"Moulton",
"Mountain City",
"Mount Calm",
"Mount Enterprise",
"Mount Pleasant",
"Mount Vernon",
"Muenster",
"Muleshoe",
"Mullin",
"Munday",
"Murchison",
"Murphy",
"Mustang",
"Mustang Ridge",
"Nacogdoches",
"Naples",
"Nash",
"Nassau Bay",
"Natalia",
"Navarro",
"Navasota",
"Nazareth",
"Nederland",
"Needville",
"Nevada",
"Newark",
"New Berlin",
"New Boston",
"New Braunfels",
"Newcastle",
"New Chapel Hill",
"New Deal",
"New Fairview",
"New Home",
"New Hope",
"New London",
"New Summerfield",
"Newton",
"New Waverly",
"Neylandville",
"Niederwald",
"Nixon",
"Nocona",
"Nolanville",
"Nome",
"Noonday",
"Nordheim",
"Normangee",
"North Cleveland",
"Northlake",
"North Richland Hills",
"Novice",
"Oak Grove",
"Oak Leaf",
"Oak Point",
"Oak Ridge",
"Oak Ridge",
"Oak Ridge North",
"Oak Valley",
"Oakwood",
"O'Brien",
"Odem",
"Odessa",
"O'Donnell",
"Oglesby",
"Old River-Winfree",
"Olmos Park",
"Olney",
"Olton",
"Omaha",
"Onalaska",
"Opdyke West",
"Orange",
"Orange Grove",
"Orchard",
"Ore City",
"Overton",
"Ovilla",
"Oyster Creek",
"Paducah",
"Paint Rock",
"Palacios",
"Palestine",
"Palisades",
"Palmer",
"Palmhurst",
"Palm Valley",
"Palmview",
"Pampa",
"Panhandle",
"Panorama Village",
"Pantego",
"Paradise",
"Paris",
"Parker",
"Pasadena",
"Pattison",
"Patton Village",
"Payne Springs",
"Pearland",
"Pearsall",
"Pecan Gap",
"Pecan Hill",
"Pecos",
"Pelican Bay",
"Penelope",
"Peñitas",
"Perryton",
"Petersburg",
"Petrolia",
"Petronila",
"Pflugerville",
"Pharr",
"Pilot Point",
"Pine Forest",
"Pinehurst",
"Pine Island",
"Pineland",
"Piney Point Village",
"Pittsburg",
"Plains",
"Plainview",
"Plano",
"Plantersville",
"Pleak",
"Pleasanton",
"Pleasant Valley",
"Plum Grove",
"Point",
"Point Blank",
"Point Comfort",
"Point Venture",
"Ponder",
"Port Aransas",
"Port Arthur",
"Port Isabel",
"Portland",
"Port Lavaca",
"Port Neches",
"Post",
"Post Oak Bend City",
"Poteet",
"Poth",
"Pottsboro",
"Powell",
"Poynor",
"Prairie View",
"Premont",
"Presidio",
"Primera",
"Princeton",
"Progreso",
"Progreso Lakes",
"Prosper",
"Providence Village",
"Putnam",
"Pyote",
"Quanah",
"Queen City",
"Quinlan",
"Quintana",
"Quitaque",
"Quitman",
"Ralls",
"Rancho Viejo",
"Ranger",
"Rankin",
"Ransom Canyon",
"Ravenna",
"Raymondville",
"Red Lick",
"Red Oak",
"Redwater",
"Refugio",
"Reklaw",
"Reno",
"Reno",
"Retreat",
"Rhome",
"Rice",
"Richardson",
"Richland",
"Richland Hills",
"Richland Springs",
"Richmond",
"Richwood",
"Riesel",
"Rio Bravo",
"Rio Grande City",
"Rio Hondo",
"Rio Vista",
"Rising Star",
"River Oaks",
"Riverside",
"Roanoke",
"Roaring Springs",
"Robert Lee",
"Robinson",
"Robstown",
"Roby",
"Rochester",
"Rockdale",
"Rockport",
"Rocksprings",
"Rockwall",
"Rocky Mound",
"Rogers",
"Rollingwood",
"Roma",
"Roman Forest",
"Ropesville",
"Roscoe",
"Rosebud",
"Rose City",
"Rose Hill Acres",
"Rosenberg",
"Ross",
"Rosser",
"Rotan",
"Round Mountain",
"Round Rock",
"Round Top",
"Rowlett",
"Roxton",
"Royse City",
"Rule",
"Runaway Bay",
"Runge",
"Rusk",
"Sabinal",
"Sachse",
"Sadler",
"Saginaw",
"St Hedwig",
"St Jo",
"St Paul",
"Salado",
"San Angelo",
"San Antonio",
"San Augustine",
"San Benito",
"Sanctuary",
"San Diego",
"Sandy Oaks",
"Sandy Point",
"San Elizario",
"San Felipe",
"Sanford",
"Sanger",
"San Juan",
"San Leanna",
"San Marcos",
"San Patricio",
"San Perlita",
"San Saba",
"Sansom Park",
"Santa Anna",
"Santa Clara",
"Santa Fe",
"Santa Rosa",
"Savoy",
"Schertz",
"Schulenburg",
"Scotland",
"Scottsville",
"Scurry",
"Seabrook",
"Seadrift",
"Seagoville",
"Seagraves",
"Sealy",
"Seguin",
"Selma",
"Seminole",
"Seven Oaks",
"Seven Points",
"Seymour",
"Shady Shores",
"Shallowater",
"Shamrock",
"Shavano Park",
"Shenandoah",
"Shepherd",
"Sherman",
"Shiner",
"Shoreacres",
"Silsbee",
"Silverton",
"Simonton",
"Sinton",
"Skellytown",
"Slaton",
"Smiley",
"Smithville",
"Smyer",
"Snook",
"Snyder",
"Socorro",
"Somerset",
"Somerville",
"Sonora",
"Sour Lake",
"South Houston",
"Southlake",
"Southmayd",
"South Mountain",
"South Padre Island",
"Southside Place",
"Spearman",
"Splendora",
"Spofford",
"Spring Branch",
"Springlake",
"Springtown",
"Spring Valley Village",
"Spur",
"Stafford",
"Stagecoach",
"Stamford",
"Stanton",
"Staples",
"Star Harbor",
"Stephenville",
"Sterling City",
"Stinnett",
"Stockdale",
"Stockton Bend",
"Stratford",
"Strawn",
"Streetman",
"Sudan",
"Sugar Land",
"Sullivan City",
"Sulphur Springs",
"Sundown",
"Sunnyvale",
"Sunray",
"Sunrise Beach Village",
"Sunset Valley",
"Sun Valley",
"Surfside Beach",
"Sweeny",
"Sweetwater",
"Taft",
"Tahoka",
"Talco",
"Talty",
"Tatum",
"Taylor",
"Taylor Lake Village",
"Taylor Landing",
"Teague",
"Tehuacana",
"Temple",
"Tenaha",
"Terrell",
"Terrell Hills",
"Texarkana",
"Texas City",
"Texhoma",
"Texline",
"The Colony",
"The Hills",
"Thompsons",
"Thorndale",
"Thornton",
"Thorntonville",
"Thrall",
"Three Rivers",
"Throckmorton",
"Tiki Island",
"Timbercreek Canyon",
"Timpson",
"Tioga",
"Tira",
"Toco",
"Todd Mission",
"Tolar",
"Tomball",
"Tom Bean",
"Tool",
"Toyah",
"Trent",
"Trenton",
"Trinidad",
"Trinity",
"Trophy Club",
"Troup",
"Troy",
"Tulia",
"Turkey",
"Tuscola",
"Tye",
"Tyler",
"Uhland",
"Uncertain",
"Union Grove",
"Union Valley",
"Universal City",
"University Park",
"Uvalde",
"Valentine",
"Valley Mills",
"Valley View",
"Van",
"Van Alstyne",
"Van Horn",
"Vega",
"Venus",
"Vernon",
"Victoria",
"Vidor",
"Vinton",
"Volente",
"Von Ormy",
"Waco",
"Waelder",
"Wake Village",
"Waller",
"Wallis",
"Walnut Springs",
"Warren City",
"Waskom",
"Watauga",
"Waxahachie",
"Weatherford",
"Webberville",
"Webster",
"Weimar",
"Weinert",
"Weir",
"Wellington",
"Wellman",
"Wells",
"Weslaco",
"West",
"Westbrook",
"West Columbia",
"Westlake",
"West Lake Hills",
"Weston",
"Weston Lakes",
"West Orange",
"Westover Hills",
"West Tawakoni",
"West University Place",
"Westworth Village",
"Wharton",
"Wheeler",
"White Deer",
"Whiteface",
"Whitehouse",
"White Oak",
"Whitesboro",
"White Settlement",
"Whitewright",
"Whitney",
"Wichita Falls",
"Wickett",
"Willis",
"Willow Park",
"Wills Point",
"Wilmer",
"Wilson",
"Wimberley",
"Windcrest",
"Windom",
"Windthorst",
"Winfield",
"Wink",
"Winnsboro",
"Winona",
"Winters",
"Wixon Valley",
"Wolfe City",
"Wolfforth",
"Woodbranch",
"Woodcreek",
"Woodloch",
"Woodsboro",
"Woodson",
"Woodville",
"Woodway",
"Wortham",
"Wylie",
"Yantis",
"Yoakum",
"Yorktown",
"Zavalla"]

def random_paragraph() -> str:
    paragraph = None
    while not paragraph:
        response = requests.get(
            'https://en.wikipedia.org/api/rest_v1/page/random/summary',
            params={
                'accept': 'application/problem+json',
            }
        ).json()
        paragraph = response['extract']
    return paragraph

def random_email(name: str):
    name = name.lower().split(' ')
    first = name[-2]
    last = name[-1]
    if random.randint(0,1):
        first = first[0]

    user = random.choice([
        first+last,
        last+first,
        first+'.'+last,
        last+'.'+first,
        first+'_'+last,
        last+'_'+first,
        last
    ])
    
    if random.randint(0,1):
        user += str(random.randint(0,9999))
    
    return user+'@'+random.choice(['gmail.com', 'hotmail.com', 'outlook.com', 'yahoo.com', 'icloud.com'])

def random_info():
    name = fake.name().replace('.', '')
    email = random_email(name)
    location = random.choice(cities)
    if random.randint(0,1):
        location = random.choice(restaurants)+random.choice([' ', ' in '])+location
    info = random_paragraph()
    return {
        'name': name,
        'email': email,
        'location': location.replace('"','').replace("'",''),
        'details': info.replace('"','').replace("'",'')
    }

def random_wait():
    time.sleep(random.randint(3,10)/10)

def main():
    print('Opening URL')
    safarictl.open_url('https://www.defendkidstx.com#popup')
    time.sleep(5)

    info = random_info()
    print('Submitting form with info:')
    print(info)
    safarictl.focus_id('et_pb_contact_name_0')
    random_wait()

    print('Inputting name')
    safarictl.keystroke(info['name'])
    random_wait()
    safarictl.keystroke('tab', text=False)
    random_wait()

    print('Inputting email')
    safarictl.keystroke(info['email'])
    random_wait()
    safarictl.keystroke('tab', text=False)
    random_wait()

    print('Inputting location')
    safarictl.keystroke(info['location'])
    random_wait()
    safarictl.keystroke('tab', text=False)
    random_wait()

    print('Inputting info')
    safarictl.keystroke(info['details'])
    random_wait()

    # Old system that instantly fills in, replaced to better fool captcha
    # safarictl.set_value_of_id('et_pb_contact_name_0', info["name"])
    # safarictl.set_value_of_id('et_pb_contact_email_0', info["email"])
    # safarictl.set_value_of_id('et_pb_contact_location_of_show_0', info["location"])
    # safarictl.set_value_of_id('et_pb_contact_other_info_0', info["info"])

    print('Submitting')
    safarictl.click_class('et_pb_contact_submit')
    time.sleep(5)
    safarictl.close_tab()
    print('Done!')

i = 1
while True:
    print('Now serving #'+str(i))
    main()
    time.sleep(5)
    i += 1